//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.PermissionPaths = new HashSet<PermissionPath>();
            this.Roles = new HashSet<Role>();
        }
    
        public int PermissionId { get; set; }
        public bool PermissionBrowse { get; set; }
        public bool PermissionEdit { get; set; }
        public bool PermissionDelete { get; set; }
    
        public virtual ICollection<PermissionPath> PermissionPaths { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
