//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionPath
    {
        public int Id { get; set; }
        public int PermissionId { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    
        public virtual Permission Permission { get; set; }
    }
}
